#!/bin/bash
t=""
i=526410
tester=""
input=""
b=""
s=""
echo "Enter bomb file"
read b
echo "Enter answer file"
read s
while [ $i -ne 654321 ]
do
       # sed -i "6s/.*/$t/g;" solution.txt
        echo "Solution Attempted: $t"
        tester=$(echo $t | ./$b $s | grep "Curses")
	if [[ $tester == *"Curses"* ]]; then
		echo "SOLUTION FOUND!"
		echo "Press Enter to write to $s"
		read input
		sed -i "6s/.*/$t/g;" $s
		echo "Exiting"
		break
	fi
        sleep 0.1
        t=$(sed 's/./& /g' <<< $i)
        ((i=i+1))
        clear
done


#find way to pause script
