#!/bin/bash
i=0
while [ $i -ne 1001 ]
do
       sed -i "7s/.*/$i/g;" solution.txt # rip to your SSD
       echo "$i"
       ./bomb solution.txt #testing the value in defusing the bomb
       sleep 1 #you can adjust the timing of the program here
       clear
       ((i=i+1)) 
done
