#!/bin/bash
t=""
i=100000
tester=""
input=""
b=""
s=""
found_solution=0
while true
do
	echo "Enter bomb file: "
	read b
	if [ -f "$b" ]; then
		break
	fi
	echo "File not found."
	echo -e
done
while true
do
	echo "Enter solution file name: "
	read s
	if [ -f "$s" ]; then
		break
	fi
	echo "File Not Found."
	echo -e
done
while [ $i -ne 654321 ]
do
        echo "Solution Attempted: $t"
        tester=$(echo $t | ./$b $s | (grep  'Cong\|Curses'))
	if [[ $tester == *"Cong"* ]]; then
		echo "SOLUTION FOUND!"
		found_solution=1
		echo -e
		echo "Make sure to save $t to $s"
		echo "Press Enter to confirm."
		read input
		echo -e
		echo "Exiting"
		break
	fi
	if [[ $tester == *"Curses"* ]]; then
		echo "SOLUTION FOUND!"
		found_solution=1
		echo -e
		echo "Make sure to save $t to $s"
		echo "Press Enter to confirm."
		read input
		echo -e
		echo "Exiting"
		break
	fi
        t=$(sed 's/./& /g' <<< $i)
        ((i=i+1))
        clear
done
if [[ $found_solution == 0 ]]; then
	echo "Solution not found."
	echo "Check to see if phase 5 is finished in solution file."
	echo "Press Enter to confirm."
	read input
	echo -e
	echo "Exiting"
fi
