#!/bin/bash
i=0
b=""
s=""
tester=""
input=""
found_input=0
echo "Enter bomb file name"
read b
echo "Enter answer file name"
read s
while [ $i -ne 1001 ]
do
	t="$i"
	echo "Solution Attempted: $t"
	tester=$(echo $t | ./$b $s | (grep "Wow"))
	if [[ $tester == *"Wow"* ]]; then
		echo "SOLUTION FOUND!"
		found_solution=1
		echo -e
		echo "Make sure to save $t to $s"
		echo "Press Enter to confirm."
		read input
		echo -e
		echo "Exiting"
		break
	fi
	((i=i+1))
	clear
done
if [[ $found_solution == 0 ]]; then
	echo "Solution not found."
	echo "Check to see if phase 6 is finished and secret flag is set in solutions file"
	echo "Check to see if bomb file and answer fire are in same directory and typed correctly"
	echo "Press Enter to confirm."
	read input
	echo -e
	echo "Exiting"
fi
